# Generated by Django 3.0.4 on 2020-07-10 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('Data_date', models.DateField(default=django.utils.timezone.now)),
                ('Data_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_ar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('Data_date', models.DateField(default=django.utils.timezone.now)),
                ('Data_update', models.DateField(auto_now=True)),
            ],
        ),

    ]
