# Generated by Django 3.0.4 on 2020-07-10 18:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200710_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='data',
            name='body_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='test_str'),
            preserve_default=False,
        ),
    ]
