# Generated by Django 3.0.4 on 2020-06-28 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('title_tag', models.CharField(default='home', max_length=255)),
                ('body', models.TextField()),
                ('Data_date', models.DateField(default=django.utils.timezone.now)),
                ('Data_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
