# Generated by Django 3.0.4 on 2020-06-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200628_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Data',
            name='category',
        ),
        migrations.RemoveField(
            model_name='Data',
            name='title_tag',
        ),
    ]
