# Generated by Django 3.0.4 on 2020-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200628_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.URLField(default='url_test'),
            preserve_default=False,
        ),
    ]
