# Generated by Django 3.0.4 on 2020-07-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_data_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='data',
            name='url',
        ),
        migrations.AlterField(
            model_name='data',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
