# Generated by Django 3.0.4 on 2020-07-11 02:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200711_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='body_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
