# Generated by Django 3.0.4 on 2020-07-11 02:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200711_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='body_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
