# Generated by Django 3.0.4 on 2020-07-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200712_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='body_json',
        ),
    ]
