# Generated by Django 3.0.4 on 2020-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_data_body_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_ar',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
