# Generated by Django 3.0.4 on 2020-07-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200717_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_ar',
        ),
    ]
