# Generated by Django 3.0.4 on 2020-07-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_data_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Data'),
        ),
    ]
