# Generated by Django 2.1.5 on 2020-11-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0002_auto_20201117_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='excerpt',
        ),
    ]
