# Generated by Django 3.0.6 on 2020-05-09 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
