# Generated by Django 3.0.6 on 2020-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='name',
        ),
    ]
